name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create the .env settings file
        working-directory: inception/
        run: cp .env.example .env

      - name: Build image & start
        run: docker-compose -f docker-compose.dev.yml up --build -d

      - name: Run tests
        run: docker exec inception-embedding-service pytest tests -v