version: "3.8"

services:
  embedding-service:
    build:
      context: .
      args:
        TARGET_ENV: dev
    ports:
      - "8005:8005"
    environment:
      - EMBEDDING_WORKERS=2
      - TRANSFORMER_MODEL_NAME=sentence-transformers/multi-qa-mpnet-base-dot-v1
      - FORCE_CPU=false
      - ENABLE_METRICS=true
      - SENTRY_DSN=
    volumes:
      - .:/app