version: "3.8"

services:
  inception-embedding-service:
    container_name: inception-embedding-service
    build:
      dockerfile: docker/Dockerfile
      context: .
      args:
        TARGET_ENV: dev
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    env_file:
      - .env