name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - uses: pre-commit/action@v3.0.0

      - name: Install UV
        uses: astral-sh/setup-uv@v4

      - name: Define a cache dependency glob
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Initialize the virtual environment
        run: uv venv

      - name: Add virtual environment to PATH
        run: echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - name: Install the project
        run: uv sync --extra cpu --frozen;

      - name: Debug paths
        run: |
          pwd
          ls -al

      - name: mypy Static Type Checker
        run: mypy inception
